import type { Config } from "tailwindcss";
import { heroui } from "@heroui/react";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Beautiful UI / GenStack semantic tokens
        gs: {
          bg: "#0A0A0A",
          elevated: "#0F0F0F",
          surface: "#141414",
          "surface-2": "#1A1A1A",
          "surface-3": "#1E1E1E",
          hover: "#222222",
          border: "rgba(255,255,255,0.08)",
          "border-strong": "rgba(255,255,255,0.14)",
          text: "#FAFAFA",
          secondary: "#A1A1AA",
          muted: "#71717A",
          accent: "#7170FF",
          "accent-hover": "#8584FF",
          "accent-soft": "rgba(113,112,255,0.14)",
          "accent-text": "#C4C3FF",
          success: "#22C55E",
          warning: "#F59E0B",
          danger: "#EF4444",
          info: "#38BDF8",
        },
        // Legacy Material-ish aliases remapped to Beautiful UI
        "on-secondary": "#A1A1AA",
        border: "rgba(255,255,255,0.08)",
        "inverse-on-surface": "#0A0A0A",
        "on-primary-fixed-variant": "#C4C3FF",
        "inverse-surface": "#FAFAFA",
        "on-primary-container": "#C4C3FF",
        "surface-container-high": "#1E1E1E",
        outline: "#71717A",
        "surface-container-low": "#141414",
        "surface-bright": "#222222",
        "on-surface": "#FAFAFA",
        "tertiary-fixed": "#FAFAFA",
        "on-surface-variant": "#A1A1AA",
        "tertiary-fixed-dim": "#A1A1AA",
        "on-error": "#450A0A",
        "on-tertiary-fixed-variant": "#A1A1AA",
        "primary-container": "#7170FF",
        "surface-container": "#1A1A1A",
        "on-tertiary": "#FAFAFA",
        error: "#EF4444",
        "outline-variant": "rgba(255,255,255,0.14)",
        "surface-tint": "#7170FF",
        "tertiary-container": "#1E1E1E",
        background: "#0A0A0A",
        muted: "#71717A",
        // primary = brand accent (CTAs); headlines use on-background / gs-text
        primary: "#7170FF",
        "secondary-fixed-dim": "#A1A1AA",
        "inverse-primary": "#4C4BB8",
        "on-secondary-fixed-variant": "#A1A1AA",
        "neutral-bg": "#0A0A0A",
        "surface-container-highest": "#222222",
        "on-secondary-container": "#A1A1AA",
        "secondary-container": "#1E1E1E",
        "primary-fixed": "#C4C3FF",
        "surface-container-lowest": "#0F0F0F",
        "on-tertiary-container": "#A1A1AA",
        "primary-fixed-dim": "#8584FF",
        surface: "#141414",
        tertiary: "rgba(255,255,255,0.06)",
        "secondary-fixed": "#FAFAFA",
        "on-secondary-fixed": "#0A0A0A",
        "error-container": "#7F1D1D",
        "on-primary-fixed": "#0A0A0A",
        "on-primary": "#FFFFFF",
        secondary: "#A1A1AA",
        "on-tertiary-fixed": "#0A0A0A",
        "on-background": "#FAFAFA",
        "on-error-container": "#FECACA",
        "surface-variant": "#1E1E1E",
        "surface-dim": "#0A0A0A",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.5rem",
        md: "0.625rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        full: "9999px",
      },
      boxShadow: {
        gs: "0 0 0 1px rgba(255,255,255,0.04), 0 8px 24px rgba(0,0,0,0.35)",
        "gs-sm": "0 0 0 1px rgba(255,255,255,0.04), 0 2px 8px rgba(0,0,0,0.25)",
      },
      spacing: {
        xs: "6px",
        sm: "14px",
        md: "24px",
        gutter: "32px",
        xl: "48px",
        lg: "40px",
        section: "96px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "monospace"],
        "headline-display": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-lg": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-md": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-sm": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "nav-sm": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "nav-md": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-lg": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-sm": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-md": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-md": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-sm": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-display": ["60px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0px", fontWeight: "500" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "nav-sm": ["12px", { lineHeight: "16px", letterSpacing: "0px", fontWeight: "400" }],
        "nav-md": ["14px", { lineHeight: "20px", letterSpacing: "0px", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0px", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-lg": ["17px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
      },
      keyframes: {
        "gs-pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.45" },
        },
        "gs-fade-in": {
          from: { opacity: "0", transform: "translateY(4px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "gs-shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        "gs-pulse": "gs-pulse 1.6s ease-in-out infinite",
        "gs-fade-in": "gs-fade-in 0.25s ease-out",
        "gs-shimmer": "gs-shimmer 1.8s linear infinite",
      },
    },
  },
  darkMode: "class",
  plugins: [heroui()],
};
export default config;
