import type { Config } from "tailwindcss";
import { heroui } from "@heroui/react";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#313030",
        "border": "#FFFFFF14",
        "inverse-on-surface": "#303030",
        "on-primary-fixed-variant": "#454747",
        "inverse-surface": "#e2e2e2",
        "on-primary-container": "#636565",
        "surface-container-high": "#2a2a2a",
        "outline": "#8e9192",
        "surface-container-low": "#1b1b1b",
        "surface-bright": "#393939",
        "on-surface": "#e2e2e2",
        "tertiary-fixed": "#e2e2e2",
        "on-surface-variant": "#c4c7c8",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#454747",
        "primary-container": "#e2e2e2",
        "surface-container": "#1f1f1f",
        "on-tertiary": "#2f3131",
        "error": "#FF5A5F",
        "outline-variant": "#444748",
        "surface-tint": "#c6c6c7",
        "tertiary-container": "#e2e2e2",
        "background": "#131313",
        "muted": "#A6A6A6",
        "primary": "#ffffff",
        "secondary-fixed-dim": "#c8c6c5",
        "inverse-primary": "#5d5f5f",
        "on-secondary-fixed-variant": "#474746",
        "neutral-bg": "#000000",
        "surface-container-highest": "#353535",
        "on-secondary-container": "#b7b5b4",
        "secondary-container": "#474746",
        "primary-fixed": "#e2e2e2",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-container": "#636565",
        "primary-fixed-dim": "#c6c6c7",
        "surface": "#121212",
        "tertiary": "#FFFFFF1A",
        "secondary-fixed": "#e5e2e1",
        "on-secondary-fixed": "#1b1b1b",
        "error-container": "#93000a",
        "on-primary-fixed": "#1a1c1c",
        "on-primary": "#2f3131",
        "secondary": "#c8c6c5",
        "on-tertiary-fixed": "#1a1c1c",
        "on-background": "#e2e2e2",
        "on-error-container": "#ffdad6",
        "surface-variant": "#353535",
        "surface-dim": "#131313"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.25rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "6px",
        "sm": "14px",
        "md": "24px",
        "gutter": "32px",
        "xl": "48px",
        "lg": "40px",
        "section": "96px"
      },
      fontFamily: {
        "headline-display": ["__interDisplay_1ec15e"],
        "headline-lg-mobile": ["Inter"],
        "label-lg": ["__inter_337fc1"],
        "headline-md": ["Inter"],
        "headline-sm": ["__interDisplay_1ec15e"],
        "nav-sm": ["Inter"],
        "nav-md": ["Inter"],
        "headline-lg": ["__interDisplay_1ec15e"],
        "label-sm": ["__inter_337fc1"],
        "body-md": ["__inter_337fc1"],
        "label-md": ["__inter_337fc1"],
        "body-sm": ["__inter_337fc1"],
        "body-lg": ["__inter_337fc1"]
      },
      fontSize: {
        "headline-display": ["60px", { "lineHeight": "75px", "letterSpacing": "0px", "fontWeight": "500" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "0px", "fontWeight": "500" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0px", "fontWeight": "500" }],
        "headline-md": ["33px", { "lineHeight": "40px", "letterSpacing": "0px", "fontWeight": "400" }],
        "headline-sm": ["24px", { "lineHeight": "26px", "letterSpacing": "0px", "fontWeight": "400" }],
        "nav-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0px", "fontWeight": "400" }],
        "nav-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0px", "fontWeight": "400" }],
        "headline-lg": ["44px", { "lineHeight": "53px", "letterSpacing": "0px", "fontWeight": "400" }],
        "label-sm": ["10px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.12px", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0px", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "21px", "letterSpacing": "-0.08px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "27px", "letterSpacing": "-0.18px", "fontWeight": "375" }]
      }
    },
  },
  darkMode: "class",
  plugins: [heroui()],
};
export default config;
